### ISSUE TITLE
Behavior of PromptInjection

### ISSUE THREAD

**Issue by Oscaner** [laiyer-ai/llm-guard#69]
Hi team,

Does the PromptInjection support languages besides English? I encountered a problem, I don't know if it's an issue or not.

<img width="1105" alt="image" src="https://github.com/laiyer-ai/llm-guard/assets/26829325/1239266b-8bc7-446c-bd51-be62e729da7c">

In the screenshot, `你好呀` means `Hello` in Chinese, but the risk score is 1.0.

When I add `!` at trailing, the risk score is 0.0, it's valid.

`你好呀` -> `你好呀!`, just like `Hello` -> `Hello!`. I don't know where it's a risk.

**Comment by asofter** [comment]
Hey @Oscaner , unfortunately, it's expected behavior because the model was trained only on English prompt injections, so it doesn't support Chinese. 

I believe there is a demand in such model, and we can look at potentially fine-tuning another model for that purpose but it will take time to understand if deberta-v3 fits as a base for that.
